<?php

/**
 * @file
 *
 * This file implements the drupal functions required to create the map browse module
 * including the menu links, theme changes, and preprocessing
 *
 */


function islandora_map_browse_init(){
    drupal_add_css(drupal_get_path('module', 'islandora_map_browse') .'/css/popup.css');
}

/*need to use hook_menu to build config menu https://drupal.org/node/1111212 see link to form code on page
 * config items: center:52.1311, -106.6353
 * 	  	 max rows: 2000
 * 	  	 baseUrl : http://islandorasev-dev.usask.ca
 *		 fedoraPrefix :  /islandora/object/
 *		 fedoraSuffix : /datastream/TN/view
 *		 objectPrefix : /islandora/object/
 *		 get pagination count from solr module setting
 */




function islandora_map_browse_theme() {

$path = drupal_get_path('module', 'islandora_map_browse');
  return array(
    'islandora_map_browse' =>  array(
      'path' => $path. '/theme',
      'variables' => array(),
      'template' => 'islandora-map-browse',
    ),
  );
}

/**
 * @param drupal page variables and hook
 * 
 * Change the theme if the current profile is a map view
 * this is done so that the page template is not displayed
 * in the colorbox window
 */

function islandora_map_browse_preprocess_page(&$variables, $hook) {
  $qparam = drupal_get_query_parameters();
  if(array_key_exists('solr_profile',$qparam)){
    if (strcasecmp($qparam['solr_profile'], 'MapGEOJSONView') == 0 || strcasecmp($qparam['solr_profile'], 'MapGEOJSONViewAll') == 0) {
      $variables['theme_hook_suggestions'][] = 'islandora_map_browse';
     //var_dump($variables);
    }
  }
}


/**
 * @param css array included in the page
 * 
 * Remove some of the css so that the colorbox works correctly
 * some themes have css that messes up the page
 */

function islandora_map_browse_css_alter(&$css){
  $qparam = drupal_get_query_parameters();
  if (array_key_exists('solr_profile',$qparam)) {
    if (strcasecmp($qparam['solr_profile'], 'MapGEOJSONView') == 0 || strcasecmp($qparam['solr_profile'], 'MapGEOJSONViewAll') == 0) {
      //These are not included, they are needed for the map
      /*
      'sites/all/modules/colorbox/styles/default/colorbox_style.css' => FALSE,
      'sites/all/modules/islandora_map_browse/css/popup.css' => FALSE,
      'misc/ui/jquery.ui.core.css' => FALSE,
      'misc/ui/jquery.ui.theme.css' => FALSE,
      'modules/shortcut/shortcut.css' => FALSE,
      'modules/toolbar/toolbar.css' => FALSE,
      sites/all/modules/colorbox/styles/default/colorbox_style.css
      sites/all/modules/islandora_map_browse/css/popup.css
      sites/all/modules/lightbox2/css/lightbox.css
      misc/ui/jquery.ui.core.css
      misc/ui/jquery.ui.theme.css
      sites/all/modules/admin_menu/admin_menu.css
      sites/all/modules/admin_menu/admin_menu.uid1.css
      sites/all/modules/admin_menu/admin_menu_toolbar/admin_menu_toolbar.css
      modules/shortcut/shortcut.css
      'sites/sho.usask.ca/themes/sho_responsive/color/colors.css' => FALSE,
      'sites/sho.usask.ca/themes/sho_responsive/style.css' => FALSE,
      */
      $exclude = array(
        'sites/sho.usask.ca/themes/sho_responsive/css/responsive-style.css' => FALSE,
        'sites/sho.usask.ca/themes/sho_responsive/css/layout.css' => FALSE,
        'sites/sho.usask.ca/themes/sho_responsive/flexslider.css' => FALSE,
        'sites/saskhistoryonline.ca/themes/sho_responsive/css/responsive-style.css' => FALSE,
        'sites/saskhistoryonline.ca/themes/sho_responsive/css/layout.css' => FALSE,
        'sites/saskhistoryonline..ca/themes/sho_responsive/flexslider.css' => FALSE,
        'themes/garland/style.css' => FALSE,
        'themes/garland/print.css' => FALSE,
        'sites/all/modules/ctools/css/ctools.css' => FALSE,
        'modules/overlay/overlay-parent.css' => FALSE,
        'modules/system/system.base.css' => FALSE,
        'modules/system/system.menus.css' => FALSE,
        'modules/system/system.messages.css' => FALSE,
        'modules/system/system.theme.css' => FALSE,
        'modules/comment/comment.css' => FALSE,
        'modules/field/theme/field.css' => FALSE,
        'sites/all/modules/islandora/css/islandora.base.css' => FALSE,
        'sites/all/modules/islandora/css/islandora.theme.css' => FALSE,
        'sites/all/modules/islandora_solution_pack_audio/css/islandora_audio.theme.css' => FALSE,
        'sites/all/modules/islandora_solution_pack_collection/css/islandora_basic_collection.base.css' => FALSE,
        'sites/all/modules/islandora_solution_pack_collection/css/islandora_basic_collection.theme.css' => FALSE,
        'sites/all/modules/islandora_solution_pack_image/css/islandora_basic_image.theme.css' => FALSE,
        'sites/all/modules/islandora_batch/css/views_table_contextual_links_fix.css' => FALSE,
        'sites/all/modules/islandora_bookmark/css/islandora_bookmark.css' => FALSE,
        'sites/all/modules/islandora_solution_pack_large_image/css/islandora_large_image.theme.css' => FALSE,
        'sites/all/modules/islandora_solution_pack_newspaper/css/islandora_newspaper.base.css' => FALSE,
        'sites/all/modules/islandora_solution_pack_newspaper/css/islandora_newspaper.theme.css' => FALSE,
        'sites/all/modules/islandora_solution_pack_pdf/css/islandora_pdf.theme.css' => FALSE,
        'sites/all/modules/islandora_solr_search/css/islandora_solr.base.css' => FALSE,
        'sites/all/modules/islandora_solr_metadata/css/islandora_solr_metadata.css' => FALSE,
        'sites/all/modules/islandora_solution_pack_video/css/islandora_video.theme.css' => FALSE,
        'modules/node/node.css' => FALSE,
        'modules/search/search.css' => FALSE,
        'modules/user/user.css' => FALSE,
        'sites/all/modules/views/css/views.css' => FALSE,
        'sites/all/modules/islandora_solr_search/css/islandora_solr.theme.css' => FALSE,
        'themes/garland/fix-ie.css' => FALSE,
      );
      $css = array_diff_key($css, $exclude);

      /*	
      foreach($css as $k => $v){
        echo $k ."<\br>";
      }
      */
    }
  }

/*
foreach($css as $k => $v){
  $ctools = drupal_get_path('module','ctools')."/css/ctools.css";
  if (strcmp($k, $ctools) != 0) {
    unset($css[$k]);
  }
}
*/
}


/**
 * @param page variables
 *
 * Find and modify the secondary display profile links
 * Add the parameters required so the link opens in a colorbox
 * 
 */

function islandora_map_browse_preprocess_islandora_solr_wrapper(&$variables) {

//<a title="Display Single Page Results on a Map" class="colorbox-load" rel="nofollow" href="/islandora/search/elevator?type=dismax&solr_profile=MapGEOJSONView&width=1000&height=800&iframe=true"><img src="/sites/all/modules/islandora_map_browse/images/google-map-logo.gif" class="islandora_map_browse_single"></a>

global $base_url;
$variables['base_url'] = $base_url;
$elements = $variables['elements'];

$dom = new DOMDocument();
$dom->loadHTML($variables['secondary_profiles']);
$finder = new DomXPath($dom);
//Look for single page
$classname="islandora_map_browse";
$nodes = $finder->query("//*[contains(concat(' ', normalize-space(@class), ' '), ' $classname ')]");
/*
if ($nodes->length == 0) {
  $classname="islandora_map_browse_single";
  $nodes = $finder->query("//*[contains(concat(' ', normalize-space(@class), ' '), ' $classname ')]");
}
*/
foreach ($nodes as $domNode) {
  if ($domNode->parentNode->nodeName == "a") {
    if (strpos($domNode->parentNode->getAttribute('href'), 'MapGEOJSONView') !== FALSE) { 
      //Add the class for the popup
      $domNode->parentNode->setAttribute('class', 'colorbox-load');
      //Get contents of href attribute, remove the attribute, re-add the attribute
      $url = $domNode->parentNode->getAttribute('href');
      $domNode->parentNode->removeAttribute('href');
      $domNode->parentNode->setAttribute('href', $url . '&width=1000&height=800&iframe=true');
      $variables['secondary_profiles'] =   $dom->saveHtml();	
    }
  }
}

// Make all variables in 'elements' available as variables in the template
// file.

foreach ($variables['elements'] as $key => $value) {
    $variables[$key] = $value;
}

// Results count.
$total = $elements['solr_total'];
$end = $elements['solr_end'];
$start = $elements['solr_start'] + ($total > 0 ? 1 : 0);

// Format numbers.
$total = number_format($total, 0, '.', ',');
$end = number_format($end, 0, '.', ',');
$start = number_format($start, 0, '.', ',');

$variables['islandora_solr_result_count'] = t('(@start - @end of @total)', array(
  '@start' => $start,
  '@end' => $end,
  '@total' => $total,
));
}



function islandora_map_browse_menu() {

  $items['admin/islandora/mapbrowse'] = array(
    'title' => 'Islandora Map Views',
    'description' => 'View collection map',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('map_browse_config'),
    'file' => 'includes/admin.form.inc',
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['browsemap'] = array(
    'title' => 'View Geolocated Items',
    'description' => 'View collection map',
    'page callback' => array('view_all_results'),
    'file' => 'includes/IslandoraSolrResultsMapView.inc',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );
return $items;

}

/**
 * Alter the theme registry so that the blank page theme 
 * can be used in the colorbox window
 *
 */

function islandora_map_browse_theme_registry_alter(&$theme_registry) {

  /*This theme change was to make the browse view look more like the solr search view*/
  // tell the theme system to look in the "templates" subdirectory within our module directory
  $theme_registry['islandora_solr_wrapper']['theme paths'] = array(0 => drupal_get_path('module', 'islandora_map_browse') . '/theme');
  $theme_registry['islandora_solr_wrapper']['theme path'] = drupal_get_path('module', 'islandra_map_browse') . '/theme';
  $theme_registry['islandora_solr_wrapper']['file'] = drupal_get_path('module', 'islandora_map_browse') . '/theme/map_display_theme.inc';
  $theme_registry['islandora_solr_wrapper']['path'] = drupal_get_path('module', 'islandora_map_browse') . '/theme';
  $theme_registry['islandora_solr_wrapper']['template'] = 'map-display';
  //dpm($theme_registry);

}



/**
 * Implements hook_islandora_solr_secondary_display()
 * Adds the two new displays
 */
function islandora_map_browse_islandora_solr_secondary_display() {
  // set path
  global $base_path;
  $path = $base_path . drupal_get_path('module', 'islandora_map_browse');
  return array(
    'MapGEOJSONView' => array(
      'name' => t('Single page GeoJSON View'),
      'module' => 'islandora_map_browse',
      'file' => 'includes/IslandoraSolrResultsMapView.inc',
      'class' => 'IslandoraSolrResultsMapView',
      'function' => 'mapGEOJSONResults',
      'description' => 'Display Single Page Results on a Map',
      'logo' => '<img src="' . $path . '/images/map60.png" class="islandora_map_browse">',
    ),
    'MapGEOJSONViewAll' => array(
      'name' => t('All Geojson'),
      'module' => 'islandora_map_browse',
      'file' => 'includes/IslandoraSolrResultsMapView.inc',
      'class' => 'IslandoraSolrResultsMapView',
      'function' => 'mapGEOJSONAll',
      'description' => 'Display Single Page Results on a Map',
      'logo' => '<img src="' . $path . '/images/map60.png" class="islandora_map_browse">',
    ),
  );
}


